### ISSUE TITLE
'css!' plugin name expands to full path when building with r.js

### ISSUE THREAD

**Issue by mbektimirov** [guybedford/require-css#133]
After r.js build empty css defines are stored with their full path to 'css!' plugin. This cause the undefined module problem. The code builded from example illustrates this issue very well:

``` javascript
// -> 'require-css/css!style/style' here, need 'css!style/style'
define('require-css/css!style/style',[],function(){});
define('require-css/css!components/component',[],function(){});
define('components/component',['css!./component'], function() {
  return {component: 'is here'};
});

// -> when here is the shorten call: 'css!style/style'
define('app',['css!style/style', 'components/component'], function(component) {
  return 'uses the component!';
});
```

The problem is in the css-builder.js , `cssAPI.write(...)` invoking with full pluginName: 'require-css/css'. I think r.js has a problem with 'pluginBuilder' option. For the quick fix you can ignore pluginName variable and put 'css!' instead:

``` javascript
write.asModule('css!' + moduleName, 'define(function(){})');
```

**Comment by IvoPereira** [comment]
@mbektimirov's solution worked for me!

Excellent!
