### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by Silfen** [guybedford/require-css#149]
This error appear in the browser after a r.js compilation (css-builder.js line 4):

``` js
var isWindows = !!process.platform.match(/^win/);
```

I fix it with :

``` js
var isWindows = typeof process !== "undefined" && !!process.platform.match(/^win/);
```

**Comment by snehilmodani** [comment]
Couldn't we still add the code as suggested by @Silfen ?

I don't understand the exclude thing completely.
