### ISSUE TITLE
Exclude external dependencies

### ISSUE THREAD

**Issue by buunguyen** [guybedford/require-css#190]
I'm running the RequireJS optimizer with vendor libs excluded via the [`empty:`](http://requirejs.org/docs/optimization.html#empty) scheme. 

The basic setup is this:

``` javascript
rjs.optimize({
  baseUrl: 'src',
  paths: {
    css: 'bower_components/require-css/css',
    'c3/c3': 'empty:'
  },
  include: ['file1.js', 'file2.js', ...]
}, ...)
```

Basically I want to exclude c3's JS and CSS from the optimized build. The `empty:` scheme works fine if I don't include files that use c3's CSS (i.e. `define('css!c3/c3')`). However, when such files are in the include list, I keep getting this error:

```
Error: Error: ENOENT, no such file or directory 'empty:.css'
```

Is there anyway for require-css to exclude vendor CSS? Thanks!

**Comment by guybedford** [comment]
It should be possible to do this via standard bundle exclusion of the plugin name itself. I'm a bit rusty these days, but perhaps `exclude: ['c3/c3']`?

**Comment by buunguyen** [comment]
Thanks for the quick reply. I just tried that but still got the same error. If I use `exclude` and remove c3/c3 from `paths`, like this:
```js
 paths: {
    css: 'bower_components/require-css/css'
  },
  exclude: ['c3/c3'],
  include: ['file1.js', 'file2.js', ...]
```
Then I'll have another error:  `Error: ENOENT, no such file or directory '/d3/d3.js'`

Basically, all 3 combinations (empty scheme, exclude, empty scheme and exclude) fail.

Also, just to make sure we're on the same page, c3 is a library that has both JS and CSS (like Bootstrap and others), not a RequireJS plugin.
