### ISSUE TITLE
Optimized build can't find this module?

### ISSUE THREAD

**Issue by mattkaye** [guybedford/require-css#191]
Hi, I'm very close to getting my build working but I get an error saying: 
```
Uncaught Error: No require-css/css.
```

I've tried a ton of different things, but can't get past this error. Would you look at my config and grunt config to see if I'm doing something wrong? Thanks in advance:

https://gist.github.com/mattkaye/a2279ef5ae45fe818a81

**Comment by Offirmo** [comment]
see https://github.com/guybedford/require-css/issues/167#issuecomment-118971335
