### ISSUE TITLE
Versions are not consistent

### ISSUE THREAD

**Issue by viskin** [guybedford/require-css#192]
Ad you download current 0.1.8 release, version of css.js inside the package is older (0.1.2).
That's the link: https://github.com/guybedford/require-css/archive/0.1.8.zip
This affects compressed release package from from github, as well as bower.
Interestingly, package.json and bower.json files contain correct version (0.1.8).
Please fix this as those who rely on bower currently get outdated version.

**Comment by guybedford** [comment]
Strange, thanks I've updated the tag.

**Comment by viskin** [comment]
I think it would be better to increment lib version, as bower does not bring the update (only people who add the library anew will get the update).
