### ISSUE TITLE
In IE8-9 onload does not fire in the second iframe

### ISSUE THREAD

**Issue by bk201-** [guybedford/require-css#196]
https://gist.github.com/bk201-/2aeb7b6ff1897d8aed2a

I run on localhost test.html.

In first iframe "onload" fires twice. In second iframe onload fires once, but css is applied.

I'm using the same method as in importLoad.

This is the second iframe
define (['css! first', 'css! second'], function () {
   // Never called because second.css is not loaded because onload not working
})

**Comment by hkaikai** [comment]
我也遇到了同样的问题，而且在ie9里面100%出现css无法加载问题
Have you solved this problem? I need help
