### ISSUE TITLE
Error load timeout for css modules

### ISSUE THREAD

**Issue by XeL077** [guybedford/require-css#215]
Hi, I'm use [Awesomium 1.7.5.1](http://www.awesomium.com/) for create desktop app.
And when I use require-css, I'm see this error.

`15:56:28 ConsoleMessage: {"EventName":"ConsoleMessage","eventType":"ConsoleMessage","LineNumber":140,"Message":"Uncaught Error: Load timeout for modules: css!c-popup-css.css_unnormalized5,css!c-popup-css\nhttp://requirejs.org/docs/errors.html#timeout","Source":"http://testhost.ru/FrontEnd/Content/libs/requirejs/require.js?t=636083313808306596"}`

If in linkLoad use function callback() - all okey.

**Comment by victordidenko** [comment]
As far as I understood, Awesomium just set unusual user agent, and require-css cannot understand it is webkit. I beleive much better way is just add feature-detect webkit, alongside with user agent detection.

**Comment by victordidenko** [comment]
@guybedford could you please assist here?
