### ISSUE TITLE
In css-builder.js path.dirname(config.out) got an error

### ISSUE THREAD

**Issue by FocusCare** [guybedford/require-css#229]
config.out maybe a function at rjs config.

**Comment by q313729286** [comment]
I ran into the same problem, which only appears when the node version is greater than 6,
My solution:
'path.dirname(config.out)'  Modified to 'path.dirname(config.out.toString()) ',
Hope can help you.

**Comment by AStoker** [comment]
Related to https://github.com/guybedford/require-css/issues/231
